In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/imdb-dataset/IMDB Dataset.csv


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [3]:
df = pd.read_csv('/kaggle/input/imdb-dataset/IMDB Dataset.csv')
df.head()
sub_df = df.head(200)
sub_df.shape
sub_df.head()
sub_df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fa

In [4]:
sub_df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fa

## convert into lowercase

In [5]:
sub_df['review'] = sub_df['review'].str.lower()

/tmp/ipykernel_13/512931614.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_df['review'] = sub_df['review'].str.lower()


In [6]:
store = sub_df['review'][1]
store
len(sub_df['review'])

200

## removing html tags

In [7]:
import re
def remove_html_tags(text):
    pattern = re.compile(r'<.*?>')
    return pattern.sub(r'',text)

sub_df['review'] = sub_df['review'].apply(remove_html_tags)
sub_df['review'][0]

/tmp/ipykernel_13/1244565235.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_df['review'] = sub_df['review'].apply(remove_html_tags)


"one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word.it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.i would say the main appeal of the show is due to the fact that it goes where other shows wo

In [8]:
# import re
# corpus = []
# for i in range (len(store)):
#     review = re.sub('[^a-zA-Z]',' ',store[i])
#     review = review.lower()
#     corpus.append(review)

In [9]:
# "".join(corpus)
# name = 'kishhlay kumar'

# names = []
# names.append(str.split(name))

## here we remove the URL's

In [10]:
import re
def remove_urls(text):
    url = re.sub(r"http\S+|www\S+|https\S+", '', text)
    return url
sub_df.loc[:,'review'] = sub_df['review'].apply(remove_urls)
sub_df['review'][0]

"one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word.it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.i would say the main appeal of the show is due to the fact that it goes where other shows wo

In [11]:
!pip install contractions

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 289.9/289.9 kB 11.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.3/118.3 kB 6.2 MB/s eta 0:00:00


In [12]:
import contractions
# text = contractions.fix("you'll")
# for i in range (len(df['review'][0])):
#     df['review'][0] = contractions.fix(i)
# df['review'][0]
def cont_fixed(message):
    text = contractions.fix(message)
    return "".join(text)
# df['review'][0].apply()

cont_fixed(" i want to become master in DS and I'll become I'll he'll ")
sub_df.loc[:,'review'] = sub_df['review'].apply(cont_fixed)

In [13]:
sub_df['review'][1]

'a wonderful little production. the filming technique is very unassuming- very old-time-bbc fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. the actors are extremely well chosen- michael sheen not only "has got all the polari" but he has all the voices down pat too! you can truly see the seamless editing guided by the references to williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. a masterful production about one of the great master\'s of comedy and his life. the realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. it plays on our knowledge and our senses, particularly with the scenes concerning orton and halliwell and the sets (particularly of their flat with halliwell\'s murals decorating every surface) are terribly well done.'

## here we remove the punctuation

In [14]:
def remove_punct(cleaned_text):
    clean = re.sub(r'[^\w\s]', '', cleaned_text)
    return clean
sub_df.loc[:,'review'] = sub_df['review'].apply(remove_punct)
sub_df['review'][0]

'one of the other reviewers has mentioned that after watching just 1 oz episode you will be hooked they are right as this is exactly what happened with methe first thing that struck me about oz was its brutality and unflinching scenes of violence which set in right from the word go trust me this is not a show for the faint hearted or timid this show pulls no punches with regards to drugs sex or violence its is hardcore in the classic use of the wordit is called oz as that is the nickname given to the oswald maximum security state penitentary it focuses mainly on emerald city an experimental section of the prison where all the cells have glass fronts and face inwards so privacy is not high on the agenda them city is home to manyaryans muslims gangstas latinos christians italians irish and moreso scuffles death stares dodgy dealings and shady agreements are never far awayi would say the main appeal of the show is due to the fact that it goes where other shows would not dare forget pretty

## Removing numbers

In [15]:
def remove_numbers(text):
    return re.sub(r'\d+', '', text)
sub_df.loc[:,'review'] = sub_df['review'].apply(remove_numbers)

In [16]:
# from textblob import TextBlob
# # from nltk

# def correct_message(message):
#     correct = TextBlob(message).correct()
#     return str(correct)

# # df['review'] = correct_message(df['review'])
# df['review'] = df['review'].apply(correct_message)

In [17]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [18]:
sub_df.loc[:,'sentiment'] = le.fit_transform(sub_df['sentiment'])

In [19]:
sub_df.shape

(200, 2)

In [20]:
# df['review'][0].split
import nltk
nltk.tokenize.word_tokenize

<function nltk.tokenize.word_tokenize(text, language='english', preserve_line=False)>

In [21]:
from nltk.stem import WordNetLemmatizer
from nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords
# from nltk.tokenize import word_tokenize
ps = PorterStemmer()
lemma = WordNetLemmatizer()
# len(df['review'])

In [22]:

# def tokenised(message):
corpus = []
for i in range(0,len(sub_df['review'])):
    review = nltk.tokenize.word_tokenize(sub_df['review'][i])
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    # review = [lemma.lemmatize(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)
# df['review'].apply(tokenised)

In [23]:
corpus[1]

'wonder littl product film techniqu unassum oldtimebbc fashion give comfort sometim discomfort sens realism entir piec actor extrem well chosen michael sheen got polari voic pat truli see seamless edit guid refer william diari entri well worth watch terrificli written perform piec master product one great master comedi life realism realli come home littl thing fantasi guard rather use tradit dream techniqu remain solid disappear play knowledg sens particularli scene concern orton halliwel set particularli flat halliwel mural decor everi surfac terribl well done'

### BAGOFWORDS

In [24]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2000,ngram_range=(1,2))

In [25]:
X = cv.fit_transform(corpus).toarray()
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [26]:
cv.vocabulary_

{'one': 1248,
 'review': 1470,
 'mention': 1108,
 'watch': 1912,
 'oz': 1275,
 'episod': 562,
 'hook': 852,
 'right': 1479,
 'exactli': 585,
 'happen': 808,
 'meth': 1111,
 'first': 673,
 'thing': 1776,
 'struck': 1696,
 'brutal': 238,
 'scene': 1520,
 'violenc': 1891,
 'set': 1566,
 'word': 1956,
 'go': 754,
 'trust': 1838,
 'show': 1593,
 'heart': 821,
 'pull': 1388,
 'punch': 1389,
 'regard': 1437,
 'drug': 509,
 'sex': 1571,
 'classic': 310,
 'use': 1874,
 'call': 247,
 'given': 750,
 'maximum': 1093,
 'secur': 1537,
 'state': 1667,
 'focus': 686,
 'mainli': 1055,
 'citi': 303,
 'prison': 1368,
 'cell': 272,
 'glass': 752,
 'front': 713,
 'face': 605,
 'high': 834,
 'agenda': 36,
 'home': 848,
 'italian': 925,
 'irish': 921,
 'death': 444,
 'deal': 441,
 'never': 1204,
 'far': 618,
 'would': 1967,
 'say': 1514,
 'main': 1053,
 'appeal': 89,
 'due': 513,
 'fact': 606,
 'goe': 757,
 'dare': 429,
 'forget': 693,
 'pretti': 1359,
 'pictur': 1315,
 'paint': 1279,
 'audienc': 120,
 'char

In [27]:
corpus[0]

'one review mention watch oz episod hook right exactli happen meth first thing struck oz brutal unflinch scene violenc set right word go trust show faint heart timid show pull punch regard drug sex violenc hardcor classic use wordit call oz nicknam given oswald maximum secur state penitentari focus mainli emerald citi experiment section prison cell glass front face inward privaci high agenda citi home manyaryan muslim gangsta latino christian italian irish moreso scuffl death stare dodgi deal shadi agreement never far awayi would say main appeal show due fact goe show would dare forget pretti pictur paint mainstream audienc forget charm forget romanceoz mess around first episod ever saw struck nasti surreal could say readi watch develop tast oz got accustom high level graphic violenc violenc injustic crook guard sold nickel inmat kill order get away well manner middl class inmat turn prison bitch due lack street skill prison experi watch oz may becom comfort uncomfort viewingthat get t

In [28]:
# sub_df.head()
X[0]

# y = pd.get_dummies(sub_df['sentiment'])

array([0, 0, 0, ..., 0, 0, 0])

In [29]:
# sub_df.head()
y = sub_df['sentiment']

In [30]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [31]:
y_train = y_train.astype('int')
y_test = y_test.astype('int')

from sklearn.naive_bayes import MultinomialNB

In [32]:
sentiment_detect = MultinomialNB()

In [33]:
sentiment_detect.fit(X_train,y_train)

MultinomialNB()

In [34]:
y_pred = sentiment_detect.predict(X_test)

In [35]:
from sklearn.metrics import accuracy_score,classification_report 
accuracy_score(y_test,y_pred)

0.675

In [36]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.72      0.75      0.73        24
           1       0.60      0.56      0.58        16

    accuracy                           0.68        40
   macro avg       0.66      0.66      0.66        40
weighted avg       0.67      0.68      0.67        40



## Logistic Regression

In [37]:
from sklearn.linear_model import LogisticRegression
lg = LogisticRegression()

In [38]:
lg.fit(X_train,y_train)

LogisticRegression()

In [39]:
accuracy = lg.score(X_test,y_test)
print('Accuracy:',accuracy)

Accuracy: 0.825


In [40]:
y_pred_lg = lg.predict(X_test)
print(classification_report(y_test,y_pred_lg))

              precision    recall  f1-score   support

           0       0.81      0.92      0.86        24
           1       0.85      0.69      0.76        16

    accuracy                           0.82        40
   macro avg       0.83      0.80      0.81        40
weighted avg       0.83      0.82      0.82        40



## TFIDF

In [41]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [42]:
tv = TfidfVectorizer(max_features=10,ngram_range=(1,2))
X_tf = tv.fit_transform(corpus).toarray()

In [43]:
X_tf

array([[0.        , 0.        , 0.4669892 , ..., 0.        , 0.71930471,
        0.47006543],
       [0.        , 0.42667217, 0.        , ..., 0.53540095, 0.54978635,
        0.        ],
       [0.46782421, 0.        , 0.        , ..., 0.44946577, 0.46154222,
        0.45242657],
       ...,
       [0.38168905, 0.        , 0.        , ..., 0.36671075, 0.        ,
        0.73825281],
       [0.        , 0.49995822, 0.15684062, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.22496796, 0.56459301, ..., 0.        , 0.        ,
        0.56831219]])

In [44]:
corpus[0]

'one review mention watch oz episod hook right exactli happen meth first thing struck oz brutal unflinch scene violenc set right word go trust show faint heart timid show pull punch regard drug sex violenc hardcor classic use wordit call oz nicknam given oswald maximum secur state penitentari focus mainli emerald citi experiment section prison cell glass front face inward privaci high agenda citi home manyaryan muslim gangsta latino christian italian irish moreso scuffl death stare dodgi deal shadi agreement never far awayi would say main appeal show due fact goe show would dare forget pretti pictur paint mainstream audienc forget charm forget romanceoz mess around first episod ever saw struck nasti surreal could say readi watch develop tast oz got accustom high level graphic violenc violenc injustic crook guard sold nickel inmat kill order get away well manner middl class inmat turn prison bitch due lack street skill prison experi watch oz may becom comfort uncomfort viewingthat get t

In [45]:
X_tf[0]

array([0.        , 0.        , 0.4669892 , 0.        , 0.        ,
       0.        , 0.20871106, 0.        , 0.71930471, 0.47006543])

In [46]:
tv.vocabulary_

{'one': 6,
 'watch': 8,
 'would': 9,
 'get': 2,
 'film': 1,
 'see': 7,
 'even': 0,
 'movi': 5,
 'make': 4,
 'like': 3}

# SVM

In [47]:
from sklearn.svm import LinearSVC
svc = LinearSVC()

In [48]:
sub_df.head()



sub_df['review'][0]

'one of the other reviewers has mentioned that after watching just  oz episode you will be hooked they are right as this is exactly what happened with methe first thing that struck me about oz was its brutality and unflinching scenes of violence which set in right from the word go trust me this is not a show for the faint hearted or timid this show pulls no punches with regards to drugs sex or violence its is hardcore in the classic use of the wordit is called oz as that is the nickname given to the oswald maximum security state penitentary it focuses mainly on emerald city an experimental section of the prison where all the cells have glass fronts and face inwards so privacy is not high on the agenda them city is home to manyaryans muslims gangstas latinos christians italians irish and moreso scuffles death stares dodgy dealings and shady agreements are never far awayi would say the main appeal of the show is due to the fact that it goes where other shows would not dare forget pretty 